/* $Header:   K:/APPS/PVCS Pro/332new/INC/ENERGY.H_V   1.2   02 May 2001 10:03:24   BKymer  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995                 */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/

/*--------------------------- INCLUDE DESCRIPTION ---------------------------

 -------------------------------- REVISIONS ---------------------------------

 Revision # Date     Author     Description
 ========== ======== ======     ===========
  0         12/12/94 Mark Laz.. Initial release 
  1.2       04-20-01 BEKymer    Added prototype for SelectEnergyWeldSequenceHH
    
     
/*
/*------------------------------ DESCRIPTION ----------------------------------*/

/*   This file defines prototypes for the energy weld mode.                    */



/*------------------------------ INCLUDE FILES --------------------------------*/



/*-------------------------------- DEFINES ------------------------------------*/



/*---------------------------- Function Prototypes ----------------------------*/

void SelectEnergyWeldSequence(void);
void SelectEnergyWeldSequenceHH(void);

