/* $Header:   K:/APPS/PVCS Pro/332new/INC/PEAKPWR.H_V   1.2   02 May 2001 10:08:44   BKymer  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995                 */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/

/*
 ---------------------------- INCLUDE DESCRIPTION ------------------------------

 -------------------------------- REVISIONS ------------------------------------

   Revision # Date     Author   Description
   ========== ======== ======   ===========
    0         12/12/94 Mark L.. Initial release 
    1.2       05-01-01 BEKymer  Add comment block, prototype for
                                 SelectPeakPowerWeldSequenceHH
                                 
                                 

 ------------------------------- DESCRIPTION -----------------------------------

   This file defines prototypes for the real time clock

 ------------------------------ INCLUDE FILES ----------------------------------
*/

/*--------------------------------- DEFINES ----------------------------------*/


/*-------------------------- Function Prototypes ---------------------------*/

void SelectPeakPowerWeldSequence(void);
void SelectPeakPowerWeldSequenceHH(void);

