/* $Header:   K:/APPS/PVCS Pro/332new/INC/TIMEMODE.H_V   1.2   20 Apr 2001 09:27:56   BKymer  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995, 1996           */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/
/*--------------------------- MODULE DESCRIPTION ---------------------------*/
/*                                                                          */
/* Module name: Timemode.h                                                  */
/*                                                                          */
/* Filename:    Timemode.h                                                  */
/*                                                                          */
/* Function Name: StateMachine for Time Weld mode                           */
/*                                                                          */
/*          Written by:   Barry E. Kymer                                    */
/*                Date:   03-15-96                                          */
/*            Language:   "C"                                               */
/*                                                                          */
/*------------------------------ REVISIONS ---------------------------------*/
/*                                                                          */
/*  Revision#  Date      Author     Description                             */
/*  =========  ========  =========  ===========                             */
/*     0       03-15-96  BEKymer    Initial release                         */
/*     1.2     04-10-01  BEKymer    Add prototype for handheld function,    */
/*                                   also add this comment block            */
/*                                                                          */
/*                                                                          */
/*-------------------------- Function Prototypes ---------------------------*/

void SelectTimeWeldSequence(void);
void SelectTimeWeldSequenceHH(void);

