/* $Header:   D:/SWLab/VMdb/2000Series/INC/VFSCRN.H_V   1.4   04 Sep 2008 20:17:36   ygupta  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1997                 */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/
/*
 ---------------------------- MODULE DESCRIPTION ----------------------------

   Module name:

   Filename: vfscrn.h


 --------------------------------- REVISIONS --------------------------------

 Rev # Date     Author Description
 ===== ======== ====== ===========
 1.0   08/12/98  BJB   Original Version
 1.1   08/21/98  BJB   Added prototype for VFConvertLineToItem()
 1.2   09/02/98  BJB   Added prototypes for new functions
 1.3   10-22-07  NHAhmed Changes done for LangTest phase 0
 1.4   09-04-08  ygupta     Cleanup for Multilanguage project.


*/

/*
 ------------------------------ INCLUDE FILES --------------------------------
*/

/*
 ------------------------------- LOCAL DEFINES -------------------------------
*/


/*
 ------------------------------- GLOBAL DATA ---------------------------------
                        (scope is global to ALL files)
*/

   
/*
 ----------------------------- FUNCTION PROTOTYPES -------------------------
*/

