/* $Header:   L:/pvcs/1000/psos332/archives/app/VPRESET3.H_v   1.0   10 Jul 1997 14:21:50   BKYMER  $ */
/****************************************************************************/ 
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995                 */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/

/*--------------------------- MODULE DESCRIPTION ---------------------------*/

/*   Module name: VPRESET_MODEL3                                            */

/*   Filename:    vpreset3.h                                                */

/*------------------------------- REVISIONS --------------------------------*/
/*                                                                          */
/*  Revision#  Date      Author       Description                           */
/*  =========  ========  ===========  ===========                           */
/*     1.00    07/09/97  BEKymer      New module, add function prototype    */
/*                                                                          */
/*                                                                          */
/*                                                                          */


/*------------------------------ DESCRIPTION -------------------------------*/



/*----------------------------- INCLUDE FILES ------------------------------*/

#include "portable.h"            /* fundamental data object types       */


UINT32 VerifyPresetModel3(void);



