/* $Header:   K:\APPS\PVCS Pro\PSS68K.222\CONFIGS\STD\errno.h_v   1.0   Mar 29 1999 13:50:56   ofingere  $ */
/* @(#) pSOSystem/68K V2.2.2: include/errno.h (std) 1.8 96/11/14 13:18:29 */
/***********************************************************************/
/*                                                                     */
/*   MODULE:  include/errno.h                                          */
/*   DATE:    96/11/14                                                 */
/*   PURPOSE: Definition of pREPC+ error codes                         */
/*                                                                     */
/*---------------------------------------------------------------------*/
/*                                                                     */
/*           Copyright 1991 - 1995, Integrated Systems, Inc.           */
/*                      ALL RIGHTS RESERVED                            */
/*                                                                     */
/*   Permission is hereby granted to licensees of Integrated Systems,  */
/*   Inc. products to use or abstract this computer program for the    */
/*   sole purpose of implementing a product based on Integrated        */
/*   Systems, Inc. products.   No other rights to reproduce, use,      */
/*   or disseminate this computer program, whether in part or in       */
/*   whole, are granted.                                               */
/*                                                                     */
/*   Integrated Systems, Inc. makes no representation or warranties    */
/*   with respect to the performance of this computer program, and     */
/*   specifically disclaims any responsibility for any damages,        */
/*   special or consequential, connected with the use of this program. */
/*                                                                     */
/*---------------------------------------------------------------------*/
/*                                                                     */
/*   This file contains definitions for the error codes that may be    */
/*   generated by the C runtime package.  The task's "errno" variable  */
/*   may contain one of these values, or a value returned by pSOS+     */
/*   or pHILE+.                                                        */
/*                                                                     */
/***********************************************************************/
/* --------------------------------- REVISIONS -------------------------

 Rev # Date     Author  Description
 ===== ======== ======  =============================================
 1.0   03/26/99 OFI     Original Version

*/

#ifdef __cplusplus
    #if __cplusplus
extern "C" {
    #endif
#endif

/*---------------------------------------------------------------------*/
/* Don't allow this file to be included more than once.                */
/*---------------------------------------------------------------------*/
#ifndef _ERRNO_H
#define _ERRNO_H

#define EMOPEN      0x3001       /* Max Number of files already open */
#define ERANGE      0x3002       /* Value out of range */
#define EBASE       0x3003       /* Invalid base */
#define EACCESS     0x3005       /* File not open for operation */
#define EMODE       0x3006       /* Invalid file mode */
#define EINVAL      0x3007       /* Invalid file type */
#define EPHILE      0x3008       /* pHILE not in system */
#define EINVTYPE    0x3009       /* Invalid buffer type - setvbuf */
#define EINVSIZE    0x300a       /* Invalid buffer size - setvbuf */
#define EPRRW       0x300b       /* Previous read/write - no setbuf */
#define ENAN        0x300d       /* Invalid floating point number */
#define EDOM        0x300e       /* Domain error - ANSI wants this to be */
				 /* defined though no pREPC+ function */
				 /* returns this error */
#define ENOSYS      0x300f       /* Unimplemented system service */

/*---------------------------------------------------------------------*/
/* Definition of errno macro                                           */
/*---------------------------------------------------------------------*/
#ifndef errno
unsigned long *errno_addr(void);
#define errno (*(int *)(errno_addr()))
#endif

#endif /* _ERRNO_H */

#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
